### PR TITLE
Fix error output when grep shell functions

### PR DESCRIPTION
**Pull request by jeffreytse**
This PR fixes the issue #56.

### CODE REVIEW

**Review by jeffreytse — COMMENTED** [review]
Here we redirect the error to `/dev/null` to quickly settle down this issue.

**Comment by djui** [comment]
Thanks @jeffreytse . Could you just adjust the PR to include the `-a` flag for `egrep`? 

Then we can merge I think.

If you have ideas for a unit test, please feel free to add it.

**Comment by jeffreytse** [comment]
Hi @djui add `-a` flag and keep the error output redirection?

**Review by jeffreytse — COMMENTED** [review]
Now the `-a` flag has been added and it can handle the binary files properly.

**Comment by djui** [comment]
Thanks @jeffreytse .

**Pull request merged**
