### PR TITLE
Replace aliases until nothing changes anymore

### PR DESCRIPTION
**Pull request by djui**
Also simplify no-change logic.

### CODE REVIEW

**Comment by pradyunsg** [comment]
@djui I'm checking this right now.

**Comment by pradyunsg** [comment]
I can confirm that this does not work in my case.

```
$ source ./alias-tips.plugin.zsh 
$ alias g=git
$ git config --global --get alias.st
status -sb
$ ZSH_PLUGINS_ALIAS_TIPS_EXPAND=1
$ git status -sb                 
Alias tip: git st
## multiple-replacements...origin/multiple-replacements
```

I'll write a test-case for this.
The alias tip should be `g st`.

**Comment by djui** [comment]
Yes, please check the latest version of [this branch](https://github.com/djui/alias-tips/tree/multiple-replacements). Yesterday I force pushed a couple of times and you might have just had bad luck.

I also added [testcases](https://github.com/djui/alias-tips/pull/16/commits/9bbb79d1d7108eb5088023ab7f47a5da0097684a) that specifically test [your scenario](https://github.com/djui/alias-tips/pull/16/files#diff-735232a718a51f54f85f8175951c2ceaR138) and they all pass for me.

See https://github.com/djui/alias-tips/issues/18 regarding:

> I was thinking about this and I realized that it could get very complicated. As in, -sb is the same as -s -b and -b -s and -bs. And there's many more edge cases...
> 
> I think one-one comparison, ignoring the option ordering is good enough. Once that is working, you should decide how much of the option-ordering related support you wish to add.

**Comment by pradyunsg** [comment]
I had *just* tested this!

It indeed does work. LGTM

**Comment by djui** [comment]
Nice, then I'll merge it.

**Comment by pradyunsg** [comment]
:tada:

**Pull request merged**
