### PR TITLE
Make command expanding the default

### PR DESCRIPTION
**Pull request by djui**
I think in the current shape the implementation is mature and also
reflects the expected behaviour.

### CODE REVIEW

**Comment by djui** [comment]
@pradyunsg Let me know if you see a problem with this.

**Comment by pradyunsg** [comment]
I want this! :smiley:

**Comment by pradyunsg** [comment]
What's `alias-tipsc`? A C/C++/some-native-language-compiled version?

**Comment by djui** [comment]
Python compiles source files during runtime for better performance. Here it looks a bit weird because it just prepends the `c` while usually it would be `alias-tips.py => alias-tips.pyc'.

**Comment by pradyunsg** [comment]
I stopped bothering about the bytecode files, `.pyc`s, since I switched to Py3. This behaviour is interesting though. I didn't think it simply added a `c`, I thought it replace `.py` with `.pyc` or appended it...

I would rename `alias-tips` to `alias-tips.py` anyway. It's never really meant to be invoked directly by anyone else. This is merely a matter of taste. The gitignore looks nicer if this rename is done.

**Comment by djui** [comment]
Well, it's called as a binary using the shebang (`#!/usr/bin/env python`) an alternative would be to call it form the zsh script like `python alias-tips.py`.

Will ponder about it. Feel free to make a pull-request for it.

**Pull request merged**
