### PR TITLE
Stop aborting the entire session

### LINKED ISSUE #37: not only does force abort the command I'm running, it aborts my entire zsh session
I don't feel like I deserve that much punishment!

### PR DESCRIPTION
**Pull request by orestisf1993**
Closes #37

I think this requires some tests. Perhaps from people with more complex configs. I don't know if SIGINTing zsh is a good practice. It could have some unwanted side effects.

### CODE REVIEW

**Comment by pradyunsg** [comment]
> I don't know if SIGINTing zsh is a good practice.

I guess SIGTERM is a better way to do it? It's kinder than KILL but harsher than SIGINT...

> I think this requires some tests.

Yes please. Having a test that ensures that the abort happens and that the entire shell doesn't die would be nice. ^.^

**Comment by orestisf1993** [comment]
I am not really sure why `SIGTERM` is a better way. Why do we want it harsher?
I think in any case you should accept the PR (or revert the previous changes) since it's an improvement from the current situation. This way, @graingert can use it and report if he is affected by any unwanted side effects.

**Comment by pradyunsg** [comment]
I think @djui should be the one doing that. :)

---

Sidenote: @djui Would you mind if I start merging PRs without taking your comments?

**Comment by djui** [comment]
@pradyunsg Please do!

**Pull request merged**
